export const restaurants = [
  { id: 'banquet', name: 'Banquet Hall', icon: '🎋' },
  { id: 'fine_dining', name: 'Fine Dining', icon: '🍷' },
  { id: 'local', name: 'Local Specialty', icon: '🍜' },
  { id: 'skewers', name: 'Skewers Shop', icon: '🍢' },
];

export const halls = [
  { id: '1', restaurant: 'banquet', name: '嵐山', capacity: 88 },
  { id: '2', restaurant: 'banquet', name: '百花亭', capacity: 60 },
  { id: '3', restaurant: 'banquet', name: '香花亭', capacity: 48 },
  { id: '4', restaurant: 'banquet', name: '嵯峨', capacity: 56 },
  { id: '5', restaurant: 'banquet', name: '福の間', capacity: 32 },
  { id: '6', restaurant: 'banquet', name: '錦', capacity: 12 },
  { id: '7', restaurant: 'banquet', name: '東山 松', capacity: 10 },
  { id: '8', restaurant: 'banquet', name: '東山 桜', capacity: 10 },
  { id: '9', restaurant: 'banquet', name: '東山 楓', capacity: 10 },
  { id: '10', restaurant: 'banquet', name: '東山 欅', capacity: 8 },
];

export const customers = [
  { id: '1', name: '田中 太郎', email: 'tanaka@email.com', phone: '090-1234-5678', visits: 12 },
  { id: '2', name: '佐藤 花子', email: 'sato@email.com', phone: '080-2345-6789', visits: 5 },
  { id: '3', name: 'Honda Ken', email: 'honda@email.com', phone: '070-3456-7890', visits: 1 },
];

export const menus = [
  { id: '1', restaurant: 'banquet', name: '会席Aコース', description: '前菜・椀物・刺身・焼物・煮物・食事・デザート', price: 4000 },
  { id: '2', restaurant: 'banquet', name: '会席Bコース', description: '特選会席 - 旬の食材を使った贅沢なコース', price: 6000 },
  { id: '3', restaurant: 'banquet', name: '飲み放題', description: '2時間飲み放題（ビール・日本酒・焼酎・ソフトドリンク）', price: 2000 },
];

export const reservations = [
  {
    id: '1',
    restaurant: 'banquet',
    customerId: '1',
    hallId: '1',
    menuId: '1',
    date: '2026-01-30',
    startTime: '12:00',
    endTime: '15:00',
    partySize: 20,
    status: 'confirmed',
    serviceNotes: '甲殻類アレルギー対応1名',
    // Extended Client Info
    agencyName: 'JTB',
    branchName: '新宿支店',
    agencyTel: '03-1234-5678',
    agencyFax: '03-1234-5679',
    agencyAddress: '東京都新宿区...',
    groupName: '鈴木様御一行',
    arrangerName: '佐藤 (JTB)',
    repName: '鈴木 一郎',
    tourConductorCount: 1,
    crewCount: 0,
    createdAt: '2026-01-15T10:00:00',
    confirmedAt: '2026-01-20T14:30:00',
    confirmedBy: 'Yamada',
    lastEditedAt: '2026-01-25T09:15:00',
    cancelledAt: null,
    cancelledBy: null,
  },
  {
    id: '2',
    restaurant: 'banquet',
    customerId: '2',
    hallId: '4',
    menuId: '2',
    date: '2026-01-30',
    startTime: '15:00',
    endTime: '18:00',
    partySize: 30,
    status: 'deposit_paid',
    serviceNotes: '',
    createdAt: '2026-01-18T11:20:00',
    confirmedAt: '2026-01-22T16:00:00',
    confirmedBy: 'Suzuki',
    lastEditedAt: '2026-01-28T13:45:00',
    cancelledAt: null,
    cancelledBy: null,
  },
  {
    id: '3',
    restaurant: 'banquet',
    customerId: '3',
    hallId: '2',
    menuId: '1',
    date: '2026-01-31',
    startTime: '18:00',
    endTime: '21:00',
    partySize: 15,
    status: 'cancelled',
    serviceNotes: 'Birthday',
    agencyName: 'HIS',
    branchName: '渋谷支店',
    agencyTel: '03-9876-5432',
    agencyFax: '03-9876-5433',
    agencyAddress: '東京都渋谷区...',
    groupName: 'Honda Group',
    arrangerName: '田中 (HIS)',
    repName: '本田 健',
    tourConductorCount: 1,
    crewCount: 1,
    createdAt: '2026-01-10T09:00:00',
    confirmedAt: null,
    confirmedBy: null,
    lastEditedAt: '2026-01-29T15:30:00',
    cancelledAt: '2026-02-01T10:00:00',
    cancelledBy: 'Manager',
  },
  {
    id: '4',
    restaurant: 'banquet',
    customerId: '1',
    hallId: '1',
    menuId: '2',
    date: '2026-02-05',
    startTime: '11:00',
    endTime: '14:00',
    partySize: 28,
    status: 'pending',
    serviceNotes: 'Vegetarian option required',
    agencyName: 'KNT',
    branchName: '池袋支店',
    agencyTel: '03-1111-2222',
    agencyFax: '03-1111-2223',
    agencyAddress: '東京都豊島区...',
    groupName: 'Yamamoto Family',
    arrangerName: '高橋 (KNT)',
    repName: '山本 大介',
    tourConductorCount: 0,
    crewCount: 0,
    createdAt: '2026-01-28T14:00:00',
    confirmedAt: null,
    confirmedBy: null,
    lastEditedAt: '2026-01-28T14:00:00',
    cancelledAt: null,
    cancelledBy: null,
  },
  {
    id: '5',
    restaurant: 'banquet',
    customerId: '2',
    hallId: '3',
    menuId: '3',
    date: '2026-02-10',
    startTime: '17:00',
    endTime: '19:30',
    partySize: 12,
    status: 'confirmed',
    serviceNotes: 'Company gathering',
    agencyName: '',
    branchName: '',
    agencyTel: '',
    agencyFax: '',
    agencyAddress: '',
    groupName: 'Tech Corp',
    arrangerName: '',
    repName: '佐藤 花子',
    tourConductorCount: 0,
    crewCount: 0,
    createdAt: '2026-01-25T09:00:00',
    confirmedAt: '2026-01-26T10:00:00',
    confirmedBy: 'Suzuki',
    lastEditedAt: '2026-01-26T10:00:00',
    cancelledAt: null,
    cancelledBy: null,
  },
  {
    id: '6',
    restaurant: 'banquet',
    customerId: '3',
    hallId: '5',
    menuId: '1',
    date: '2026-01-20',
    startTime: '12:00',
    endTime: '14:00',
    partySize: 6,
    status: 'completed',
    serviceNotes: 'VIP guest',
    agencyName: '',
    branchName: '',
    agencyTel: '',
    agencyFax: '',
    agencyAddress: '',
    groupName: 'VIP Lunch',
    arrangerName: '',
    repName: 'Honda Ken',
    tourConductorCount: 0,
    crewCount: 0,
    createdAt: '2026-01-05T11:00:00',
    confirmedAt: '2026-01-06T15:00:00',
    confirmedBy: 'Yamada',
    lastEditedAt: '2026-01-06T15:00:00',
    cancelledAt: null,
    cancelledBy: null,
  },
  {
    id: '7',
    restaurant: 'banquet',
    customerId: '1',
    hallId: '1',
    menuId: '2',
    date: '2026-02-01',
    startTime: '18:00',
    endTime: '21:00',
    partySize: 25,
    status: 'confirmed',
    serviceNotes: 'Today\'s booking',
    agencyName: 'JTB',
    branchName: '新宿支店',
    agencyTel: '03-1234-5678',
    agencyFax: '03-1234-5679',
    agencyAddress: '東京都新宿区...',
    groupName: 'Todays Group',
    arrangerName: '佐藤 (JTB)',
    repName: '田中 太郎',
    tourConductorCount: 1,
    crewCount: 0,
    createdAt: '2026-01-20T10:00:00',
    confirmedAt: '2026-01-25T14:30:00',
    confirmedBy: 'Yamada',
    lastEditedAt: '2026-01-30T09:15:00',
    cancelledAt: null,
    cancelledBy: null,
  },
  {
    id: '8',
    restaurant: 'banquet',
    customerId: '2',
    hallId: '2',
    menuId: '1',
    date: '2026-03-03',
    startTime: '11:00',
    endTime: '14:00',
    partySize: 20,
    status: 'pending',
    serviceNotes: 'Hinamatsuri Special',
    agencyName: '',
    branchName: '',
    agencyTel: '',
    agencyFax: '',
    agencyAddress: '',
    groupName: 'Girls Day Out',
    arrangerName: '',
    repName: '佐藤 花子',
    tourConductorCount: 0,
    crewCount: 0,
    createdAt: '2026-02-01T12:00:00',
    confirmedAt: null,
    confirmedBy: null,
    lastEditedAt: '2026-02-01T12:00:00',
    cancelledAt: null,
    cancelledBy: null,
  },
];
